# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-24 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_sponsorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='network',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sponsor',
            field=models.CharField(default='Jimmoney', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofmembership',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastlogin',
            field=models.DateTimeField(),
        ),
    ]
