# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-24 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190324_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastlogin',
        ),
    ]
