# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-27 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='adminstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='staffstatus',
            field=models.BooleanField(default=False),
        ),
    ]
