# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-27 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190327_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='accname',
            field=models.CharField(default='Jim', max_length=1000),
        ),
        migrations.AddField(
            model_name='request',
            name='accno',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='bankname',
            field=models.CharField(default='Jim', max_length=250),
        ),
        migrations.AddField(
            model_name='request',
            name='level',
            field=models.CharField(default=2, max_length=10),
        ),
    ]
