# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-30 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_request_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Request')),
            ],
        ),
    ]
