# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-28 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
