# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0004_staff_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
