# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0005_registrationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcode',
            name='dateofmembership',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
