# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-30 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jimcontrol', '0006_registrationcode_dateofmembership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationcode',
            old_name='dateofmembership',
            new_name='date',
        ),
    ]
